= 個人情報保護指針
TAOドライブ株式会社
v1.0, 2017/10/4, 制定

TAOドライブ株式会社は、「個人情報の保護に関する法律」（「個人情報保護法」）に基づく個人データの適正な取扱いの確保について組織として取り組むために、本個人情報保護指針を定めます。
なお、当社の提供する各種サービス個別に個人情報保護指針を制定している場合には、個別の指針が優先されるものとします。

== 第１条（定義）

本規約において使用する以下の用語は、各々以下に定める意味を有するものとします。

（１）「当社」とは、TAOドライブ株式会社を意味します。

（２）「当社サービス」とは、当社が提供する各種サービスを意味します。

（３）「利用者」とは、当社が事業を行うにあたり、各種の申し込みの受付、アンケート調査、商談、契約の締結などの機会を通じて、また、不動産登記簿、商業登記簿、電話帳などの一般に公開されている媒体から、住所・氏名・郵便番号・電話番号・FAX番号・メールアドレスなどの個人情報を取得した個人または法人を意味します。

（４）「利用者情報」とは、利用者の識別に係る情報、通信サービス上の行動履歴、その他利用者のスマートフォン・PC等の端末において利用者または利用者の端末に関連して生成または蓄積された情報であって、本指針に基づき当社が収集するものを指します。

== 第２条（関係法令・ガイドライン等の遵守）
当社は、個人情報保護法その他の法令及び「個人情報の保護に関する法律についてのガイドライン」その他のガイドラインを遵守して、個人データの適正な取扱いを行います。

== 第３条（利用目的）
当社は、「個人情報の保護に関する法律」を遵守し、当社が行う事業に関するご案内・ご提案、契約の締結・履行、アフターサービスの実施、利用者への連絡・通信、新しい商品・サービスの開発、および利用者に有益と思われる情報の提供などのために、利用者の個人情報を利用させていただきます。

具体的には、下記のような目的などで利用させていただきます。

* 利用者からのご意見・ご感想をいただくため
* 利用者からのお問合せや資料請求などに対応するため
* 市場調査や新しい商品・サービスの開発のため
* 各種イベント・セミナー・キャンペーン・会員制サービスなどの案内のため
* 電子メール配信サービスや刊行物などの発送のため
* 当社または提携先で取り扱っている商品やサービスに関する情報の提供のため
* 会計監査上の確認作業のため
* その他当社の事業に付帯・関連する事項のため

== 第４条（通知・公表又は同意取得の方法、利用中止要請の方法）
利用者は、利用者情報の全部または一部についてその利用の停止を求めることができ、この場合、当社は速やかに、当社の定めるところに従い、その利用を停止します。なお利用者情報の項目によっては、その収集または利用が当社サービスの前提となるため、当社所定の方法により当社サービスを終了した場合に限り、当社はその収集を停止します。

== 第５条（安全管理措置に関する事項）
当社は、個人データについて、漏えい、滅失又はき損の防止等、その管理のために必要かつ適切な安全管理措置を講じます。また、個人データを取り扱う従業者や委託先（再委託先等を含みます。）に対して、必要かつ適切な監督を行います。個人データの安全管理措置に関しては、別途「個人情報取扱規程」において具体的に定めております。

== 第６条（第三者提供）
当社は、利用者情報のうち、個人情報については、個人情報保護法その他の法令に基づき開示が認められる場合を除くほか、あらかじめ利用者の同意を得ないで、第三者に提供しません。但し、次に掲げる場合はこの限りではありません。

1. 当社が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合
1. 合併その他の事由による事業の承継に伴って個人情報が提供される場合
1. 情報収集モジュール提供者へ個人情報が提供される場合
1. 国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって、利用者の同意を得ることによって当該事務の遂行に支障を及ぼすおそれがある場合
1. その他、個人情報保護法その他の法令で認められる場合

== 第７条（共同利用）
当社は、以下のとおり利用者の個人情報を共同利用します。
①共同して利用される個人情報の項目 +
第２条に定める項目 +
②共同して利用する者の範囲 +
当社サービスの開発・運用・利用者のサポート・改善・修正を当社から委託もしくは共同で実施する法人もしくは個人 +
③共同して利用する者の利用目的 +
当社サービスの開発・運用・利用者のサポート・改善・修正 +
④利用者情報の管理について責任を有する者の氏名または名称 +
TAOドライブ株式会社

== 第８条（個人情報の開示）
当社は、利用者から、個人情報保護法の定めに基づき個人情報の開示を求められたときは、利用者ご本人からのご請求であることを確認の上で、利用者に対し、遅滞なく開示を行います（当該個人情報が存在しないときにその旨を通知いたします。）。但し、個人情報保護法その他の法令により、当社が開示の義務を負わない場合は、この限りではありません。なお、個人情報の開示につきましては、手数料（1件あたり500円）を頂戴しておりますので、あらかじめご了承ください。

== 第９条（個人情報の訂正・利用停止）
（１）当社は、利用者から下記の要請を受けた場合には、利用者ご本人からのご請求であることを確認の上で遅滞なく必要な調査を行い、その結果に基づき、個人情報の内容の訂正または利用停止を行い、その旨を利用者に通知します。なお、合理的な理由に基づいて訂正または利用停止を行わない旨の決定をしたときは、利用者に対しその旨を通知いたします。

1. 個人情報が真実でないという理由によって個人情報保護法の定めに基づきその内容の訂正を求められた場合
1. あらかじめ公表された利用目的の範囲を超えて取り扱われているという理由または偽りその他不正の手段により収集されたものであるという理由により、個人情報保護法の定めに基づきその利用の停止を求められた場合

（２）当社は、利用者から、利用者の個人情報について消去を求められた場合、当社が当該請求に応じる必要があると判断した場合は、利用者ご本人からのご請求であることを確認の上で、個人情報の消去を行い、その旨を利用者に通知します。

（３）個人情報保護法その他の法令により、当社が訂正等または利用停止等の義務を負わない場合は、前2項の規定は適用されません。

== 第１０条（お問い合わせ窓口）
ご意見、ご質問、苦情のお申出その他利用者情報の取扱いに関するお問い合わせは、下記の窓口までお願い致します。

住所： 東京都千代田区一番町２－２　TAOドライブ株式会社 +
担当部署：クラウドアプリケーション部 +
E-mail：info@taodrive.com

== 第１１条（本指針の変更手続き）
当社は、利用者情報の取扱いに関する運用状況を適宜見直し、継続的な改善に努めるものとし、必要に応じて、本指針を変更することがあります。変更した場合には、Webページに最新版を開示することで利用者に通知いたします。但し、法令上ユーザの同意が必要となるような内容の変更の場合は、当社所定の方法でユーザの同意を得るものとします。

== 附則
本指針は平成２９年１０月４日から施行します。
